### ISSUE TITLE
Download link missing

### ISSUE THREAD

**Issue by RaymondZaagsma** [NicklasAhlberg/Windows-Startmenu-Creator-Tool#2]
Nicklas,

The download link is missing for the Windows Start Menu Creator Tool.

There is nothing to the right

Download latest release to the right -->

**Comment by NicklasAhlberg** [comment]
Hi! 

You will find the latest release under the "releases" section over at this URL:
https://github.com/NicklasAhlberg/Windows-Startmenu-Creator-Tool

Here is a directlink to download the latest version: https://github.com/NicklasAhlberg/Windows-Startmenu-Creator-Tool/releases/download/1.0.5.0/Windows-Startmenu-Creator-Tool.zip

**Comment by RaymondZaagsma** [comment]
Nicklas,

Thx I totally missed that, releases on the right part.

**Comment by NicklasAhlberg** [comment]
No worries at all :)

I'll close this issue. Let me know if you require any help with the startmenu creator tool - I am happy to help

Regards

NIcklas Ahlberg
